name: 'Custom Env Vars'

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Funday
  testvar: value-1

jobs:
   mainjob:
      name: 'Print the env vars'
      runs-on: ubuntu-latest

      env:
        Greeting: Dear
        testvar: value-2
        First_Name: Student 
      
      steps:
      - name: print-values-of-env-vars
        id: step_one
        run:  |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "testvar $testvar"
          echo "testvar ${{env.testvar}}"  
          echo "$action_state=yellow" >> $GITHUB_ENV  
            
      - name: Use-the-value
        id: step_two
        run:  |
           echo "${{ env.action_state }}"  
        

      
